services:
  - type: web
    name: mlflow-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: mlflow server --backend-store-uri postgresql://mlflow_db_zpf4_user:0J6HuL2s9Cs8BPti8V0Zx1lyocJJIcva@dpg-cvfejk1svqrc73d0n5sg-a:5432/mlflow_db_zpf4 --default-artifact-root /tmp/mlruns --host 0.0.0.0 --port $PORT --serve-artifacts
